[package]
name = "emuman"
description = "Utility to managing emulator ROM files."
version = "0.9.2"
authors = ["Brian Langenberger <bjl@usa.net>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
structopt = "0.2"
roxmltree = "0.7"
rusqlite = "0.20"
bitstream-io = "0.8"
sha1 = {version = "0.6", features=["std"]}
rayon = "1.1"
prettytable-rs = "0.8"
walkdir = "2"
directories = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.10"
