[package]
name = "emuman"
description = "Utility for managing emulator ROM files."
version = "1.14.0"
authors = ["Brian Langenberger <bjl@usa.net>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tuffy/emuman"
edition = "2018"

[dependencies]
structopt = "0.3"
roxmltree = "0.14"
rusqlite = "0.25"
sha1 = "0.6"
rayon = "1.5"
prettytable-rs = "0.8"
walkdir = "2"
directories = "4.0"
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.11"
fxhash = "0.2"
nohash-hasher = "0.2"
indicatif = {version = "0.16", features=["with_rayon"]}
zip = "0.5"
once_cell = "1.8"
dashmap = "4.0"
