[package]
name = "emuman"
description = "Utility for managing emulator ROM files."
version = "1.1.0"
authors = ["Brian Langenberger <bjl@usa.net>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tuffy/emuman"
edition = "2018"

[dependencies]
structopt = "0.2"
roxmltree = "0.7"
rusqlite = "0.20"
sha1 = {version = "0.6", features=["std"]}
rayon = "1.1"
prettytable-rs = "0.8"
walkdir = "2"
directories = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.10"
